### PR TITLE
Release 0.7.1

### PR DESCRIPTION
**Pull request by forrestfwilliams**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by forrestfwilliams** [comment]
@conda-forge-admin, please rerender

**Comment by jhkennedy** [comment]
@forrestfwilliams when adding a contributor, you only need to add it to the recipe -- Conda-forge's CI/CD will update the readme and codeowners

**Comment by forrestfwilliams** [comment]
@jhkennedy thanks, I'll keep that in mind. Everything looks right to me now, but I'm seeing that GitHub is complaining about a bug in the `.github/CODEOWNERS` file. Can you spot what's going on?

**Comment by jhkennedy** [comment]
@forrestfwilliams I believe it's complaining because Andrew isn't part of this repo yet, so he can't be a code owner (he doesn't have access) -- when conda-forge's CI/CD runs, it will add him as a maintainer to this repo, and then he can be listed.

I've reverted your changes to the CODEOWNERS and README. Generally, you should only have to edit things in the `recipe/` directory.

**Comment by forrestfwilliams** [comment]
Thanks!

**Pull request merged**
